### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dengxk1234** [Icepenguins101/charms-bar-port#11]
It seems the new code has something wrong when I compile it. In the file "CharmsBar.xaml.cs" line 995 and 4536, the name "ActiveCharm" isn't defined.
Any fix for it? Thanks!
<img width="764" alt="image" src="https://github.com/Icepenguins101/charms-bar-port/assets/96613876/1d54ff08-05d6-4cad-a35b-685598958d8b">

**Comment by Icepenguins101** [comment]
That was because I was rushing to fix another similar issue and neglected to patch the file together. I’ll update this asap.
