### ISSUE TITLE
Charms Bar's buttons doesn't show up

### ISSUE THREAD

**Issue by NotMaddIsMadd** [Icepenguins101/charms-bar-port#7]
![dasdasdasdasdas](https://github.com/Icepenguins101/charms-bar-port/assets/116704923/d5a6ec7e-2c87-46b4-9121-450c71f33bef)
this is not edited

**Comment by Icepenguins101** [comment]
The bug can be fixed if you swipe again from the top right or bottom right. Haven’t been able to fix this whatsoever.

**Comment by NotMaddIsMadd** [comment]
it's still doesn't show up.

**Comment by Icepenguins101** [comment]
Are you using the new hotfix or a touch device?

**Comment by NotMaddIsMadd** [comment]
no i'm using a PC without a touch screen & i'm using the new hotfix.

**Comment by Icepenguins101** [comment]
I’ll see what I can do.

**Comment by NotMaddIsMadd** [comment]
oh wait nvm, I didn't realize the new hotfix. I tried download it but when I open it up there's 13 errors with the code CS0103.

**Comment by Icepenguins101** [comment]
Can I see some screenshots of the error log? I think this hotfix was done in a rush.

**Comment by NotMaddIsMadd** [comment]
sure,

![image](https://github.com/Icepenguins101/charms-bar-port/assets/116704923/973a0580-5076-4faf-9217-dc8b3af43eb9)

**Comment by Icepenguins101** [comment]
I see, I either forgot to update the Charms Menu file or neglected to bring in some definitions for it, I’ll patch this tomorrow.

**Comment by NotMaddIsMadd** [comment]
It works now!!
